import Logo from "../assets/png/logo.png";
import SmartHomeIcon from "../assets/png/smart-home.png";
import ShoppingCartIcon from "../assets/png/shopping-cart.png";
import ChevLeft from "../assets/png/chev-left.png";
import ChevRight from "../assets/png/chev-right.png";
import BoxIcon from "../assets/png/box.png";
import CirclePlusIcon from "../assets/png/circle-plus.png";
import StarIcon from "../assets/png/star.png";
import BellIcon from "../assets/png/bell.png";
import SalesStatIcon from "../assets/png/salesStat.png";
import ArrowUpIcon from "../assets/png/arrow-up.png";
export { Logo, SmartHomeIcon, ShoppingCartIcon, BellIcon, ArrowUpIcon, SalesStatIcon, ChevLeft, ChevRight, BoxIcon, CirclePlusIcon, StarIcon };
