import Logo from "../assets/png/logo.png";
import SmartHomeIcon from "../assets/png/smart-home.png";
import ShoppingCartIcon from "../assets/png/shopping-cart.png";
import ChevLeft from "../assets/png/chev-left.png";
import ChevRight from "../assets/png/chev-right.png";
import BoxIcon from "../assets/png/box.png";
import CirclePlusIcon from "../assets/png/circle-plus.png";
import StarIcon from "../assets/png/star.png";
import BellIcon from "../assets/png/bell.png";
import SalesStatIcon from "../assets/png/salesStat.png";
import ArrowUpIcon from "../assets/png/arrow-up.png";
import YenIcon from "../assets/png/yen.png";
import USAIcon from "../assets/png/usa.png";
import BrazilIcon from "../assets/png/brazil.png";
import AUSIcon from "../assets/png/australia.png";
import ChevUpIcon from "../assets/png/chevron-up.png";
import ChevDownIcon from "../assets/png/chevron-down.png";
import CircleBlueIcon from "../assets/png/circle-blue.png";
import ChevronLeftIcon from "../assets/png/chevron-left.png";
import ChevronRightIcon from "../assets/png/chevron-right.png";

export { CircleBlueIcon, ChevronLeftIcon, ChevronRightIcon, AUSIcon, BrazilIcon, ChevUpIcon, ChevDownIcon, Logo, SmartHomeIcon, ShoppingCartIcon, USAIcon, YenIcon, BellIcon, ArrowUpIcon, SalesStatIcon, ChevLeft, ChevRight, BoxIcon, CirclePlusIcon, StarIcon };
