export const COMPANY_NAME = "JoBins";
export const SIDEBAR_MENU_RESPONSIVE_WIDTH = 1167;
export const TOTAL_SALES_TITLE = "Total Sales & Costs"
export const TOTAL_SLAES_TITLE = "Total Sales & Costs"
export const LAST_SEVEN_DAYS = "Last 7 days"
export const VS_LAST_SEVEN_DAYS = "vs last 7 days"
export const TOTAL_PROFIT_TITLE = "Total Profit"
export const PERSONAL_INFORMATION_TITLE = "Personal Information"
export const SHIPPING_ADDRESS_TITLE = "Shipping address"